<?php
/**
 * @file multimediabs_example.module
 * Multimediabs example module
 */

//DRUPAL HOOKS

/**
 * Implementation of hook_menu().
 */
function multimediabs_example_menu() { 
  // This is the minimum information you can provide for a menu item.
  $items['admin/settings/multimediabs_example'] = array(
    'title' => t('Multimediabs Example admin'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('multimediabs_example_settings_form'),
    'access arguments' => array('administer multimediabs_example settings'),
    'file' => 'inc/multimediabs_example.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/content/multimediabs_example/importer'] = array(
    'title' => t('Multimediabs Example importer'),
    'page callback' => 'multimediabs_example_importer',
    'page arguments' => array(4),
    'access arguments' => array('administer multimediabs_example settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of hook_perm()
 */
function multimediabs_example_perm() {
  return array('administer multimediabs_example settings');
}
/**
 * Implementation of hook_block().
 */
function multimediabs_example_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {

    case 'list':
      $blocks[0]['info'] = 'Multimediabs example block';

      return $blocks;

    case 'view':
      if ($delta == 0) {
        $block['subject'] = t('Multimediabs example block title');
        $block['content'] = theme('multimediabs_example_message', variable_get('multimediabs_example_text', 'Hello mbs'));
      }
     
      return $block;
  }    
}


/**
 * Implementation of hook_nodeapi().
 */
function multimediabs_example_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'update':
      drupal_set_message('You are updating a node');
      dsm($node);
      break;
    case 'insert':
      //drupal_set_message('You are creating node with title @title', array('@title' => $node->title));      
      break;
    case 'view':
      if (arg(0) == 'node' && is_numeric(arg(1))) {
        drupal_set_message('You are viewing a full node');
      }
      
      break;
  }
}


/**
 * Implementation of hook_user().
 */
function multimediabs_example_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'login':
      drupal_set_message($account->name . ' logged in');
      break;
  }
}

/**
 * Implementation of hook_theme
 */
function multimediabs_example_theme($existing, $type, $theme, $path) {
  return array(
    'multimediabs_example_message' => array(
      'arguments' => array(
        'message' => NULL,
      ),
      'template' => 'tpl/multimediabs_example',      
    ), 
    'multimediabs_example_import_page' => array(
      'arguments' => array(
        'title' => NULL, 'body' => NULL, 'link' => NULL,
      ),
      'template' => 'tpl/multimediabs_example_import_page',      
    ), 
  );
}

//CALLBACKS

/**
 * Import functionality
 */
function multimediabs_example_importer($arg) {
  if ($arg == 'go') {
    $nodes = multimediabs_example_import();
    
    foreach ($nodes as $node) {
      $link = l($node->title, 'node/'.$node->nid);
      switch ($node->import_status) {
        case 'updated':        
          $list[] = t('Node updated !link', array('!link' => $link));
          break;
        case 'created':
          $list[] = t('Node created !link', array('!link' => $link));
          break;
      }       
    } 
    drupal_set_message(t('Import finished')); 
  }

  //Create page  
  $title = t('Nodes import');
  $body = theme('item_list', $list);
  $link = l('Start import', 'admin/content/multimediabs_example/importer/go');
    
  $output = theme('multimediabs_example_import_page', $title, $body, $link);
  
  return $output;
}

/**
 * Import worker
 */
function multimediabs_example_import() {  
  $result = db_query("SELECT * FROM {multimediabs_example}");
  
  while($row = db_fetch_object($result)) {
    $fields = explode(';', $row->text);
    
    $nid = db_result(db_query("SELECT nid FROM {node} WHERE title = '%s'", 'forbidden'));
    if (!$nid) {
      $node = new stdClass();
      $node->type = 'movie';
      $node->title = $fields[0];
      $node->body = $fields[1];
      $node->status = 1;
      $node->promote = variable_get('multimediabs_example_promoted', true);
      
      $node->import_status = 'created';
      
      $node = node_submit($node);
      node_save($node);
    }
    else {
      $node = node_load($nid);
      $node->title = $fields[0];
      $node->body = $fields[1];
      
      $node->import_status = 'updated';  
    } 
    $nodes[] = $node;
  }    

  return $nodes;
}